title: Jonathan L. Moran
url: "https://jonathanloganmoran.github.io"
#baseurl: "/researcher"
baseurl: "/jonathanloganmoran"

markdown: kramdown
#ins_logo: "./bits-logo.png"
#plugins: -jekyll-seo-tag

favicon: yes
favicons_location: "assets/images/favicons"

site_images: "assets/images/site_images"

avatar_images: "assets/images/author"
avatar: yes

author: "Jonathan Logan Moran"

tracking_id: "G-762VGX3R51"

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

# Includes an icon in the footer for each username you enter
footer-links:
  github: jonathanloganmoran
  linkedin: jonathanloganmoran
  gmail: jonathan.moran107@gmail.com

# Permalink placeholders for blog posts
categories: tests, blog

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Portfolio"
   link: '/jonathanloganmoran/portfolio'
 - name: "Education"
   link: "/jonathanloganmoran/education"
 - name: "Experience"
   link: "/jonathanloganmoran/experience"
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "/jonathanloganmoran/contact"
