remote_theme: ankitsultana/researcher@gem

title: Jonathan L. Moran
url: "http://jonathanlmoran.com/"
#baseurl: "/researcher"
baseurl: ""

markdown: kramdown
# Markdown Processors
kramdown:
    input: GFM
    auto_ids: true
    math_engine: mathjax
    math_engine_opts: {}
    parse_block_html: true
    # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        default_lang: python
        css_class: 'highlight'
        block:
            line_numbers: false
     # Use existing pygments syntax highlighting css
     #css_class: 'highlight'
    
#ins_logo: "./bits-logo.png"

favicon: yes
favicons_location: "assets/images/favicons"

site_images: "assets/images/site_images"

avatar: yes
avatar_random: yes              # Randomises avatar image, selected from `avatar_images` folder
avatar_images: "assets/images/author"

author: "Jonathan Logan Moran"

timezone: America/Los_Angeles

# Google Analytics support
tracking: yes
tracking_id: UA-199808329-1     # Default UA tag, GA tag is also used in default.html

# Jekyll plugins
plugins:
    - jekyll-seo-tag
    - jekyll-remote-theme
    - jekyll-sitemap

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

# Includes an icon in the footer for each username you enter
footer-links:
    github: jonathanloganmoran
    linkedin: jonathanloganmoran
    gmail: jonathan.moran107@gmail.com

# Permalink placeholders for blog posts
categories: tests, blog

sass:
    style: compressed
    sass_dir: _sass

nav:
- name: "Portfolio"
  link: "/portfolio"
- name: "Education"
  link: "/education"
- name: "Experience"
  link: "/experience"
- name: "Resume"
  link: "/resume.pdf"
- name: "Contact"
  link: "/contact"